### ISSUE TITLE
TikTokの画像とURLを用意

### ISSUE THREAD

**Issue by nobu74658** [nobu74658/task_tock#4]

**Comment by junki-pw** [comment]
<img width="240" alt="スクリーンショット 2024-10-30 8 40 11" src="https://github.com/user-attachments/assets/ac6a7481-7664-4b89-8597-2ce20637b32a">

https://www.tiktok.com/@naenano/video/7277502689041239298

<img width="238" alt="スクリーンショット 2024-10-30 8 39 03" src="https://github.com/user-attachments/assets/d6e49365-4942-427b-8f9c-2564fb048a89">

https://www.tiktok.com/@aine_nakano/video/7396973923855830279

<img width="241" alt="スクリーンショット 2024-10-30 8 38 27" src="https://github.com/user-attachments/assets/26cec7d7-967a-401f-851b-d1aeda8f1b34">

https://www.tiktok.com/@siorisandayo2/video/7431113090344799495

**Comment by nobu74658** [comment]
done
